ai/ai/urls.py
from django.contrib import admin
from django.urls import path

from ai.views import AiView, AiAPIView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ai/test/", AiView.as_view(), name='test'),
    path("ai/api/test/", AiAPIView.as_view(), name='ai'),
]

post/urls.py
from django.urls import path

from post.views import PostWriteView, PostDetailView, PostListView, PostDeleteView, PostUpdateView

app_name = 'post'

urlpatterns = [
    path('write/', PostWriteView.as_view(), name='write'),
    path('detail/', PostDetailView.as_view(), name='detail'),
    path('list/', PostListView.as_view(), name='list'),
    path('delete/', PostDeleteView.as_view(), name='delete'),
    path('update/', PostUpdateView.as_view(), name='update')
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from oauth.views import OAuthLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls-web')),
    path('mobile/member/', include('member.urls-app')),
    path('accounts/', include('allauth.urls')),
    path('oauth/', include('oauth.urls')),
    path('post/', include('post.urls')),
    path('replies/', include('reply.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
import math
import datetime
import os

from django.conf import settings
from django.db import models

from member.models import Member
from post.managers import PostManager
from project.period import Period


class Post(Period):
    post_title = models.CharField(max_length=200, null=False, blank=True)
    post_content = models.CharField(max_length=500, null=False, blank=True)
    post_read_count = models.BigIntegerField(default=0)
    status = models.BooleanField(default=True)
    member = models.ForeignKey(Member, null=False, on_delete=models.PROTECT)

    objects = models.Manager()
    enabled_objects = PostManager()

    class Meta:
        db_table = 'tbl_post'
        ordering = ['-id']

    def get_absolute_url(self, page, order, type, keyword):
        return f'/post/detail/?id={self.id}&page={page}&order={order}&type={type}&keyword={keyword}'

    def change_date_format(self):
        now = datetime.datetime.now()
        create_date = self.created_date
        gap = math.floor((now - create_date).seconds / 60)

        if gap < 1:
            return "방금 전"

        if gap < 60:
            return f"{gap}분 전"

        gap = math.floor(gap / 60)

        if gap < 24:
            return f"{gap}시간 전"

        gap = math.floor(gap / 24)

        if gap < 31:
            return f"{gap}일 전"

        gap = math.floor(gap / 31)

        if gap < 12:
            return "${gap}개월 전"

        gap = math.floor(gap / 12)
        return f"{gap}년 전"


class PostFile(Period):
    post = models.ForeignKey(Post, null=False, on_delete=models.CASCADE)
    path = models.ImageField(null=False, blank=False, upload_to='post/%Y/%m/%d')
    preview = models.BooleanField(default=False)

    class Meta:
        db_table = 'tbl_post_file'

    def delete(self, *args, **kwargs):
        super(PostFile, self).delete(*args, **kwargs)
        # ImageField객체의 path: 절대경로
        # ImageField객체의 url: /upload/부터의 경로(MEDIA_ROOT부터의 경로)
        os.remove(self.path.path)












post/views.py
import math

from django.db import transaction
from django.db.models import Q
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import View

from member.models import Member
from post.models import Post, PostFile


class PostWriteView(View):
    def get(self, request):
        type = request.GET.get('type', '')
        keyword = request.GET.get('keyword', '')
        order = request.GET.get('order', 'recent')
        page = request.GET.get('page', 1)

        context = {
            'type': type,
            'keyword': keyword,
            'order': order,
            'page': page
        }

        return render(request, 'post/write.html', context)

    @transaction.atomic
    def post(self, request):
        type = request.POST.get('type', '')
        keyword = request.POST.get('keyword', '')
        order = request.POST.get('order', 'recent')
        page = request.POST.get('page', 1)

        datas = request.POST
        files = request.FILES

        datas = {
            'post_title': datas['post-title'],
            'post_content': datas['post-content'],
            'member': Member.objects.get(id=request.session['member']['id'])
        }

        post = Post.objects.create(**datas)

        for key in files:
            PostFile.objects.create(post=post, path=files[key], preview=key == 'upload1')

        return redirect(post.get_absolute_url(page, order, type, keyword))


class PostDetailView(View):
    def get(self, request):
        type = request.GET.get('type', '')
        keyword = request.GET.get('keyword', '')
        order = request.GET.get('order', 'recent')
        page = request.GET.get('page', 1)

        post = Post.objects.get(id=request.GET['id'])
        post.post_read_count += 1
        post.updated_date = timezone.now()
        post.save(update_fields=['post_read_count', 'updated_date'])

        context = {
            'type': type,
            'keyword': keyword,
            'order': order,
            'post': post,
            'page': page
        }

        return render(request, 'post/detail.html', context)


class PostListView(View):
    def get(self, request):
        page = request.GET.get('page', 1)
        type = request.GET.get('type', '')
        keyword = request.GET.get('keyword', '')
        order = request.GET.get('order', 'recent')
        page = int(request.GET.get('page', 1))

        condition = Q()
        if type:
            for t in list(type):
                if t == 't':
                    condition |= Q(post_title__contains=keyword)

                elif t == 'c':
                    condition |= Q(post_content__contains=keyword)

                elif t == 'w':
                    condition |= Q(member__member_name__contains=keyword)

        row_count = 5
        offset = (page - 1) * row_count
        limit = page * row_count
        total = Post.enabled_objects.filter(condition).count()
        page_count = 5
        end_page = math.ceil(page / page_count) * page_count
        start_page = end_page - page_count + 1
        real_end = math.ceil(total / row_count)
        end_page = real_end if end_page > real_end else end_page

        if end_page == 0:
            end_page = 1

        context = {
            'total': total,
            'order': order,
            'start_page': start_page,
            'end_page': end_page,
            'page': page,
            'real_end': real_end,
            'page_count': page_count,
            'type': type,
            'keyword': keyword,
        }
        ordering = '-id'
        if order == 'popular':
            ordering = '-post_read_count'

        context['posts'] = list(Post.enabled_objects.filter(condition).order_by(ordering))[offset:limit]

        return render(request, 'post/list.html', context)


class PostDeleteView(View):
    @transaction.atomic
    def get(self, request):
        type = request.GET.get('type', '')
        keyword = request.GET.get('keyword', '')
        order = request.GET.get('order', 'recent')
        page = request.GET.get('page', 1)

        post = Post.objects.get(id=request.GET['id'])
        post.status = False
        post.updated_date = timezone.now()
        post.save(update_fields=['status', 'updated_date'])

        print(post.postfile_set.all())
        for post_file in PostFile.objects.filter(post_id=post.id):
            post_file.delete()

        return redirect(f'/post/list?page={page}&order={order}&type={type}&keyword={keyword}')


class PostUpdateView(View):
    def get(self, request):
        type = request.GET.get('type', '')
        keyword = request.GET.get('keyword', '')
        order = request.GET.get('order', 'recent')
        page = request.GET.get('page', 1)

        post = Post.objects.get(id=request.GET['id'])
        context = {
            'post': post,
            'post_files': list(post.postfile_set.values('path')),
            'type': type,
            'keyword': keyword,
            'order': order,
            'page': page
        }
        return render(request, 'post/update.html', context)

    @transaction.atomic
    def post(self, request):
        type = request.POST.get('type', '')
        keyword = request.POST.get('keyword', '')
        order = request.POST.get('order', 'recent')
        page = request.POST.get('page', 1)

        id = request.GET['id']
        datas = request.POST
        deleted_files = request.POST.getlist('deleted')
        files = request.FILES

        datas = {
            'post_title': datas['post-title'],
            'post_content': datas['post-content'],
        }

        post = Post.objects.get(id=id)
        post.post_title = datas['post_title']
        post.post_content = datas['post_content']
        post.updated_date = timezone.now()
        post.save(update_fields=['post_title', 'post_content', 'updated_date'])

        for key in files:
            PostFile.objects.create(post=post, path=files[key], preview=key == 'upload1')

        for path in deleted_files:
            PostFile.objects.get(path=path).delete()

        return redirect(post.get_absolute_url(page, order, type, keyword))





















templates/post/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="{% static 'public/images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'post/css/post.css' %}">
    <link rel="stylesheet" href="{% static 'public/css/header.css' %}">
    {% block static %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="modal">
        <div class="warn-modal">
            <div id="content-wrap"></div>
        </div>
    </div>
    {% include 'post/header.html' %}
    {% block content %}{% endblock %}
</body>
    {% block js %}{% endblock %}
</html>














templates/post/detail.html
{% extends 'post/base.html' %}
{% load static %}

{% block title %}상세보기{% endblock %}

{% block content %}
    <main id="post">
        <section id="post-banner">
            <div><a href="/post/write?page={{ page }}&order={{ order }}&type={{ type }}&keyword={{ keyword }}"><img src="{% static 'public/images/post_banner.png' %}"></a></div>
        </section>
        <section id="info-wrap">
            <article id="info-container">
                <h6 class="info">게시글 상세보기</h6>
                <section class="order">
                    <a href="/post/list?page={{ page }}&order={{ order }}&type={{ type }}&keyword={{ keyword }}">목록으로</a>
                    {% if request.session.member.id == post.member.id %}
                        <a href="/post/update/?id={{ post.id }}&page={{ page }}&order={{ order }}&type={{ type }}&keyword={{ keyword }}" class="update">수정</a>
                        <a href="/post/delete/?id={{ post.id }}&page={{ page }}&order={{ order }}&type={{ type }}&keyword={{ keyword }}" class="delete">삭제</a>
                    {% endif %}
                </section>
            </article>
            <section id="detail-title">
                <h2>{{ post.post_title }}</h2>
            </section>
            <section id="detail-info">
                <div class="profile">
                    {% if post.member.memberfile_set.all|length != 0 %}
                        {% for file in post.member.memberfile_set.all %}
                            <img src="/upload/{{ file.path }}" width="15px">
                        {% endfor %}
                    {% else %}
                        <img src="{% static 'public/images/default-profile.png' %}" width="15px">
                    {% endif %}
                    <h6 class="writer">{{ post.member.member_name }}</h6>
                </div>
                <hr>
                <h6 id="detail-read-count">조회 {{ post.post_read_count }}</h6>
                <hr>
            </section>

            <h5 id="content">
                {{ post.post_content }}
            </h5>
            <div>
                {% for postfile in post.postfile_set.all %}
                    <a href="">
                        <img src="/upload/{{ postfile.path }}" width="100%" class="file-list">
                    </a>
                {% endfor %}
            </div>
            <section id="reply-write-wrap" style="display: block;">
                <div class="profile">
                    <div>
                        {% if request.session.member_files %}
                            {% for file in request.session.member_files %}
                                <img src="/upload/{{ file.path }}" width="15px">
                            {% endfor %}
                        {% else %}
                            <img src="{% static 'public/images/default-profile.png' %}" width="15px">
                        {% endif %}
                    </div>
                    <h6 class="writer">{{ request.session.member.member_name }}</h6>
                </div>
                <textarea id="reply-content" cols="30" rows="1" placeholder="내 댓글"></textarea>
                <button id="reply-write">작성완료</button>
            </section>
            <section id="replies-wrap">
                <ul></ul>
                <button type="button" id="more-replies">
                	<div>더보기</div>
                	<div><img src="{% static 'public/images/plus.png' %}" width="24"></div>
                </button>
            </section>
        </section>
    </main>
{% endblock %}

{% block js %}
    <script>
        const csrf_token = '{{ csrf_token }}';
        const post_id = '{{ post.id }}'
        const memberId = '{{ request.session.member.id }}'
    </script>
    <script src="{% static 'reply/js/reply-module.js' %}/"></script>
    <script src="{% static 'reply/js/reply.js' %}/"></script>
{% endblock %}













templates/post/header.html
{% load static %}
<header>
    <div id="header">
        <div id="logo">
            <img src="{% static 'public/images/logo.png' %}">
        </div>
        <div id="search">
            <div class="search-wrap">
                <form action="/post/list" name="search-form">
                    <div>
                        <select name="type">
                            <option value="" {% if type == "" %}selected{% endif %}>전체</option>
                            <option value="t" {% if type == "t" %}selected{% endif %}>제목</option>
                            <option value="c" {% if type == "c" %}selected{% endif %}>내용</option>
                            <option value="w" {% if type == "w" %}selected{% endif %}>작성자</option>
                            <option value="cw" {% if type == "cw" %}selected{% endif %}>내용 또는 작성자</option>
                        </select>
                    </div>
                    <div class="search-container">
                        <input type="text" autocomplete="off" name="keyword" value="{{ keyword }}">
                        <button type="submit" onclick=""><img src="{% static 'public/images/search.png' %}"
                                width="20px"></button>
                    </div>
                </form>
            </div>
        </div>
        <div id="category">
            <div class="profile" onclick="location.href='{% url 'member:mypage' %}'">
                {% if request.session.member_files %}
                    {% for file in request.session.member_files %}
                        <img src="/upload/{{ file.path }}" width="30">
                    {% endfor %}
                {% else %}
                    <img src="{% static 'public/images/default-profile.png' %}" width="30">
                {% endif %}
            </div>
            <div>
                {% if request.session.member.member_type == 'project' %}
                    <a href="{% url 'member:logout' %}">로그아웃</a>
                {% else %}
                    <a href="/accounts/logout">로그아웃</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

templates/post/list.html
{% extends 'post/base.html' %}
{% load static %}

{% block title %}목록{% endblock %}

{% block content %}
    <main id="post">
        <section id="post-banner">
            <div><a href="/post/write?page={{ page }}&order={{ order }}&type={{ type }}&keyword={{ keyword }}"><img src="{% static 'public/images/post_banner.png' %}"></a></div>
        </section>
        <section id="info-wrap">
            <article id="info-container">
                <h6 class="info">게시글 목록<br>{{ total }}개</h6>
                <section class="order">
                    <a href="/post/list?type={{ type }}&keyword={{ keyword }}">최신순</a>
                    <a href="/post/list/?order=popular&type={{ type }}&keyword={{ keyword }}">인기순</a>
                </section>
            </article>
            <section id="content-wrap">
                <ul>
                    {% for post in posts %}
                        <li>
                            <div>
                                <a href="/post/detail/?id={{ post.id }}&page={{ page }}&order={{ order }}&type={{ type }}&keyword={{ keyword }}">
                                    <section class="content-container">
                                        <div class="profile">
                                            <div>
                                                {% if post.member.memberfile_set.all|length != 0 %}
                                                    {% for file in post.member.memberfile_set.all %}
                                                        <img src="/upload/{{ file.path }}" width="15px">
                                                    {% endfor %}
                                                {% else %}
                                                    <img src="{% static 'public/images/default-profile.png' %}" width="15px">
                                                {% endif %}
                                            </div>
                                            <h6 class="writer">{{ post.member.member_name }}</h6>
                                        </div>
                                        <h4 class="title">{{ post.post_title }}</h4>
                                        <h6 clss="post-info">
                                            <span class="read-count">조회 {{ post.post_read_count }}</span>
                                            <span>·</span>
                                            <span class="date">{{ post.change_date_format }}</span>
                                        </h6>
                                    </section>
                                    {% for postfile in post.postfile_set.all %}
                                        {% if postfile.preview %}
                                            <img src="/upload/{{ postfile.path }}" class="preview">
                                        {% endif %}
                                    {% endfor %}
                                </a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div id="paging-wrap">
                    {% if start_page > 1 %}
                        {% if order == 'popular' %}
                            <a href="/post/list/?page={{ start_page|add:-1 }}&order=popular&type={{ type }}&keyword={{ keyword }}" class="paging paging-move"><img src="{% static 'public/images/prev.png' %}" width="15px"></a>
                        {% else %}
                            <a href="/post/list/?page={{ start_page|add:-1 }}&type={{ type }}&keyword={{ keyword }}" class="paging paging-move"><img src="{% static 'public/images/prev.png' %}" width="15px"></a>
                        {% endif %}
                        
                    {% endif %}
                    {% for i in "x"|rjust:page_count %}
                        {% if forloop.counter0|add:start_page <= real_end%}
                            {% if page == forloop.counter0|add:start_page %}
                                <a href="javascript:void(0)" class="paging paging-checked">{{ forloop.counter0|add:start_page}}</a>
                            {% else %}
                                {% if order == 'popular' %}
                                    <a href="/post/list/?page={{ forloop.counter0|add:start_page }}&order=popular&type={{ type }}&keyword={{ keyword }}" class="paging">{{ forloop.counter0|add:start_page}}</a>
                                {% else %}
                                    <a href="/post/list/?page={{ forloop.counter0|add:start_page }}&type={{ type }}&keyword={{ keyword }}" class="paging">{{ forloop.counter0|add:start_page}}</a>
                                {% endif %}
                                
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    {% if end_page < real_end %}
                        {% if order == 'popular' %}
                            <a href="/post/list/?page={{ end_page|add:1 }}&order=popular&type={{ type }}&keyword={{ keyword }}" class="paging paging-move"><img src="{% static 'public/images/next.png' %}" width="15px"></a>
                        {% else %}
                            <a href="/post/list/?page={{ end_page|add:1 }}&type={{ type }}&keyword={{ keyword }}" class="paging paging-move"><img src="{% static 'public/images/next.png' %}" width="15px"></a>
                        {% endif %}
                        
                    {% endif %}
                    <div></div>
                </div>
            </section>
        </section>
    </main>
{% endblock %}

{% block js %}
{% endblock %}

templates/post/write.html
{% extends 'post/base.html' %}
{% load static %}

{% block title %}작성하기{% endblock %}
{% block content %}
    <main id="board">
        <div class="modal">
            <div class="warn-modal">
                <div id="content-wrap"></div>
            </div>
        </div>
        <section id="info-wrap">
            <article id="info-container">
                <h6 class="info">게시글 작성하기</h6>
                <section class="order">
                    <a href="/post/list?page={{ page }}&order={{ order }}&type={{ type }}&keyword={{ keyword }}">목록으로</a>
                </section>
            </article>
            <form action="{% url 'post:write' %}" method="post" name="write" enctype="multipart/form-data">
                <input type="hidden" name="order" value="{{ order }}">
                <input type="hidden" name="page" value="{{ page }}">
                <input type="hidden" name="type" value="{{ type }}">
                <input type="hidden" name="keyword" value="{{ keyword }}">
                {% csrf_token %}
                <legend>
                    <h3>
                        게시글을 <span class="text-accent2">바른말</span>로 <span class="text-accent1">이쁘게</span> 작성해보세요
                    </h3>
                </legend>
                <div id="write-title-wrap" class="wrap">
                    <div class="profile write-profile">
                        {% if request.session.member_files %}
                            {% for file in request.session.member_files %}
                                <img src="/upload/{{ file.path }}" width="15px">
                            {% endfor %}
                        {% else %}
                            <img src="{% static 'public/images/default-profile.png' %}" width="15px">
                        {% endif %}
                        <h6 class="writer">{{ request.session.member.member_name }}</h6>
                    </div>
                    <label>제목</label>
                </div>
                <span class="title area">
                    <textarea name="post-title" rows="1" maxlength="30" placeholder="멋진 제목을 작성해보세요." onkeyup="checkLength(this, 30)"></textarea>
                    <div class="textarea-count">0/30</div>
                </span>
                <div id="write-content-wrap" class="wrap">
                    <label>내용</label>
                </div>
                <span class="content area">
                    <textarea name="post-content" rows="3" maxlength="5000" placeholder="여러분의 글솜씨를 보여주세요." onkeyup="checkLength(this, 5000)"></textarea>
                    <div class="textarea-count">0/5,000</div>
                </span>
                <div class="attach-wrap">
                    <label for="upload1" class="attach">
                        <img src="" class="thumbnail">
                        <div class="x">
                            <img src="{% static 'public/images/x.png' %}">
                        </div>
                        <h6 class="plus">+</h6>
                        <h6>대표 이미지</h6>
                    </label>
                    <label for="upload2" class="attach">
                        <img src="" class="thumbnail">
                        <div class="x">
                            <img src="{% static 'public/images/x.png' %}">
                        </div>
                        <h6 class="plus">+</h6>
                        <h6>이미지 추가</h6>
                    </label>
                    <label for="upload3" class="attach">
                        <img src="" class="thumbnail">
                        <div class="x">
                            <img src="{% static 'public/images/x.png' %}">
                        </div>
                        <h6 class="plus">+</h6>
                        <h6>이미지 추가</h6>
                    </label>
                    <label for="upload4" class="attach">
                        <img src="" class="thumbnail">
                        <div class="x">
                            <img src="{% static 'public/images/x.png' %}">
                        </div>
                        <h6 class="plus">+</h6>
                        <h6>이미지 추가</h6>
                    </label>
                </div>
                <input type="file" name="upload1" id="upload1" class="upload" style="display: none;">
                <input type="file" name="upload2" id="upload2" class="upload" style="display: none;">
                <input type="file" name="upload3" id="upload3" class="upload" style="display: none;">
                <input type="file" name="upload4" id="upload4" class="upload" style="display: none;">
                <article class="warn-wrap">
                    <h5 class="warn-title">게시글을 등록하기 전에 확인해주세요!</h5>
                    <ul>
                        <li>게시글 목록에서는 <span class="text-accent1">대표 이미지만 나타나요.</span></li>
                        <li>등록한 게시글은 모든 이용자가 볼 수 있으며, <span class="text-accent1">댓글은 작성자만 삭제할 수 있어요.</span></li>
                        <li>본인이 등록한 게시글은 언제든지 수정 및 삭제가 가능해요.</li>
                        <li>
                            이런 게시글은 본인의 의사와 상관없이 삭제될 수 있어요.
                            <ul class="inner">
                                <li>비속어와 상대방을 비방하는 내용이 있는 경우</li>
                                <li>광고 및 홍보 내용이 있는 경우</li>
                                <li>정치적인 내용이 있는 경우</li>
                            </ul>
                        </li>
                        <li>제목이 길면, 직접 작성한 제목과 다르게 올라갈 수 있어요.</li>
                        <li>게시글 내용을 즐거운 Django 마케팅 및 광고 목적으로 활용하는 것에 동의합니다.</li>
                        <li>즐거운 Django 게시글 내용에 대한 법률적 책임이 없습니다.</li>
                    </ul>
                </article>
                <div id="check-agree">
                    <label class="check-agree-wrap">
                        <section>
                            <input type="checkbox" name="agree">
                            <span class="checkbox">
                                <img src="{% static 'public/images/check_all.png' %}" width="15px">
                            </span>
                            <p class="h5">유의사항을 모두 확인했으며, 동의합니다.</p>
                        </section>
                    </label>
                </div>
                <button type="button" name="ok" class="ok-button">게시글 등록하기</button>
            </form>
        </section>
    </main>
{% endblock %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://rawgit.com/jackmoore/autosize/master/dist/autosize.min.js"></script>
    <script src="{% static 'post/js/write.js' %}"></script>
{% endblock %}